### ISSUE TITLE
Now working on ubuntu 15.10

### ISSUE THREAD

**Issue by Levino** [tutumcloud/cli#87]
Hey there, Ubuntu 15.10 with Python 2.7.10. On ```tutum login --debug``` I get this:

```shell
INFO:python-tutum:Request: GET https://dashboard.tutum.co/api/v1/auth/ {'Content-Type': 'application/json', 'User-Agent': 'tutum-cli/0.20.2 python-tutum/0.20.2'} {'auth': <requests.auth.HTTPBasicAuth object at 0x7fcb5e6e9a10>}
'module' object has no attribute 'HTTPMessage'
```

**Comment by tifayuki** [comment]
By goggling, it looks that the issue is caused by the conflict of `future` and `urllib3`. Can you pasted the output of `pip freeze`?

**Comment by Levino** [comment]
```
BzrTools==2.6.0
Chameleon==2.22
Cheetah==2.4.4
Cython==0.23.3
Electrum==2.5.4
IPy==0.81
PAM==0.4.2
Pillow==2.5.3
PyJWT==1.0.0
PyYAML==3.10
SOAPpy==0.12.22
SecretStorage==2.1.2
SocksiPy-branch==1.1
Twisted==14.0.0
Twisted-Core==15.2.1
Twisted-Web==15.2.1
adium-theme-ubuntu==0.3.4
ago==0.0.6
apt-xapian-index==0.46
argparse==1.2.1
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.3.2
blinker==1.3
bzr==2.7.0.dev1
bzr-builddeb==2.8.6
ccsm==0.9.12.2
certifi==14.5.14
cffi==1.1.2
characteristic==14.3.0
chardet==2.3.0
colorama==0.3.3
compizconfig-python==0.9.12.2
configobj==5.0.6
coverage==3.7.1
cryptography==1.0.1
debtags==2.0
defer==1.0.6
defusedxml==0.4.1
dirspec==13.10
distro-info===0.14build1
dnspython==1.12.0
docker-py==1.2.3
duplicity==0.7.2
ecdsa==0.13
enum34==1.0.4
euca2ools==3.1.0
feedparser==5.1.3
flake8==2.1.0
future==0.14.3
html5lib==0.999
httplib2==0.9
idna==2.0
ipaddress==1.0.14
keyring==4.0
launchpadlib==1.10.3
lazr.restfulclient==0.13.4
lazr.uri==1.0.3
lockfile==0.10.2
lptools==0.2.0
lxml==3.4.4
mccabe==0.2.1
miniupnpc==1.9
mock==1.0.1
ndg-httpsclient==0.4.0
nose==1.3.4
oauth==1.0.1
oauthlib==1.0.0
oneconf==0.3.8
pbkdf2==1.3
pep8==1.5.7
piston-mini-client==0.7.5
ply==3.7
protobuf==2.6.1
pyOpenSSL==0.15.1
pyasn1==0.1.8
pyasn1-modules==0.0.7
pybitcointools==1.1
pycountry==1.8
pycparser==2.14
pycrypto==2.6.1
pycups==1.9.73
pydns==2.3.6
pyelliptic==1.5.3
pyflakes==0.8.1
pygobject==3.16.2
pygpgme==0.3
pyserial==2.7
pysqlcipher==2.6.3.dev1
python-apt==1.0.1
python-dateutil==2.4.2
python-debian==0.1.27
python-debianbts==1.11
python-gnupg==0.3.6
python-obelisk==0.1.3
python-tutum==0.20.2
pyxdg==0.25
pyzmq==14.3.1
qrcode==5.1
reportbug===6.6.5ubuntu1
requestbuilder==0.2.3
requests==2.7.0
service-identity==14.0.0
simplejson==3.7.3
six==1.9.0
slowaes==0.1a1
software-center-aptd-plugins==0.0.0
system-service==0.1.6
tabulate==0.7.2
tlslite==0.4.8
tornado==4.0.1
tutum==0.20.2
uTidylib==0.2
ubuntu-dev-tools===0.155-ubuntu3
unity-lens-photos==1.0
urllib3==1.11
vboxapi==1.0
wadllib==1.3.2
websocket-client==0.32.0
wheel==0.26.0
wsgiref==0.1.2
wstools==0.4.3
xdiagnose==3.8.1
yenc==0.4.0
zope.interface==4.1.2
```

Thank you @tifayuki . I know nothing about python.

**Comment by tifayuki** [comment]
As mentioned here: https://github.com/django-haystack/django-haystack/issues/1231
upgrading future version can fix the issue. I will update the requirement as soon as possible.

**Comment by Levino** [comment]
So I wait? It is not tooo urgent. I can continue working with the gui for a while.

**Comment by tifayuki** [comment]
I will publish a new version with the fix, and you can do `pip install -U tutum` when the new version is available.  Or, you can install tutum in a virtualenv:
```
pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install tutum
```
This will run tutum in a "sandbox" like environment to avoid global package conflicts.

**Comment by Levino** [comment]
When will this be published?

**Comment by tifayuki** [comment]
A new version of 0.21.1 with `future==0.15` has been published

**Comment by Levino** [comment]
Thank you!
